# Generated by Django 5.2 on 2025-05-02 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_artist_top_five'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='top_five',
            field=models.BooleanField(default=False),
        ),
    ]
