# Generated by Django 5.2 on 2025-05-02 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_concert_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='concert',
            name='review',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
