# Generated by Django 5.2 on 2025-05-01 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_artist_top_five_artist_user_concert_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='top_five',
            field=models.BooleanField(),
        ),
    ]
