# Generated by Django 5.2 on 2025-05-02 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_artist_top_five'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='location',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
