# Generated by Django 5.2.1 on 2025-06-02 22:48

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_concert_image_alter_concert_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
            ],
        ),
        migrations.AlterField(
            model_name='concert',
            name='image',
            field=models.ImageField(default=1, upload_to='', verbose_name="blank=True, null=True, upload_to='images/'"),
            preserve_default=False,
        ),
    ]
