# Generated by Django 5.2.1 on 2025-06-16 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_library'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='photo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.concert'),
            preserve_default=False,
        ),
    ]
