# Generated by Django 5.2.1 on 2025-06-17 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_library_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='library',
            old_name='photo',
            new_name='concert',
        ),
    ]
