# Generated by Django 5.2.1 on 2025-06-17 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_rename_photo_library_concert'),
    ]

    operations = [
        migrations.RenameField(
            model_name='concert',
            old_name='artist_name',
            new_name='name',
        ),
    ]
