# Generated by Django 5.2.1 on 2025-06-18 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_rename_artist_name_concert_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concert',
            name='image',
        ),
    ]
